---
title: "p8105_hw5_yw3439"
author: "Qetsiyah Wang"
date: "11/15/2020"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE)

library(tidyverse)
library(dplyr)
```

# Problem 1 - Washington Homicides

```{r}
homicide = read_csv("homicide-data.csv")
```
  The raw dataset contains `r ncol(homicide)` variables and `r nrow(homicide)` observations. Major variables contain: information about victims in each homicide, including their names, `r str_remove(colnames(homicide)[5:7], pattern = "victim_")`, and reported case information, such as `r colnames(homicide)[8:12]` and `r colnames(homicide)[2]`. 

```{r}

cases = homicide %>%
  mutate(
    city_state = paste(city, ",", state)
  ) %>%
  select(-city, -state) %>%
  group_by(city_state, disposition) %>%
  summarize(n = n()) %>%
  pivot_wider(
    names_from = disposition,
    values_from = n
  ) %>%
  janitor::clean_names() %>%
  mutate(
    total_cases = sum(closed_by_arrest, closed_without_arrest, open_no_arrest, na.rm = TRUE),
    unsolved_cases = sum(closed_without_arrest, open_no_arrest, na.rm = TRUE)
  ) %>%
  select(-closed_by_arrest, -closed_without_arrest, -open_no_arrest)

```
knitr::kable(cases)

```{r}

prop_test = 

```








